# Generated by Django 4.0.2 on 2022-03-02 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='show_on_list',
            field=models.BooleanField(default=True),
        ),
    ]
